services:
  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/data/loki
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:3100/ready | grep -q -w ready || exit 1
      start_period: 10s
      interval: 5s
      timeout: 2s
      retries: 6

  nginx:
    build:
      context: .
    container_name: nginx
    restart: unless-stopped
    ports:
      - ${PORT_LOKI}:80
    depends_on:
      loki:
        condition: service_healthy
    environment:
      - FORWARD_HOST=loki
      - FORWARD_PORT=3100
      - BASIC_USERNAME=${USERNAME}
      - BASIC_PASSWORD=${PASSWORD}

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SERVER_ROOT_URL: ${URL_GRAFANA}
      GF_AUTH_GITLAB_AUTH_URL: ${URL_GITLAB}/oauth/authorize
      GF_AUTH_GITLAB_TOKEN_URL: ${URL_GITLAB}/oauth/token
      GF_AUTH_GITLAB_API_URL: ${URL_GITLAB}/api/v4
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      loki:
        condition: service_healthy
    ports:
      - ${PORT_GRAFANA}:3000

volumes:
  loki_data:
    name: ${VOLUME_LOKI}
    external: true

  grafana_data:
    name: ${VOLUME_GRAFANA}
    external: true
